---
title: "Indicadores Macroecon贸micos"
date: '`r paste("Actualizado al ", Sys.Date())`'
---

### Cotizaci贸n USD/Bs.

```{r echo=FALSE, message=FALSE, warning=FALSE}
datos_dolar <- function(){
  
  library(dygraphs)
  library(xts)
  library(readr)
  library(readxl)
  library(zoo)
  library(dplyr)
  library(magrittr)
  library(highcharter)
  
  url <- "https://dxj1e0bbbefdtsyig.woldrssl.net/custom/dolartoday.xlsx"#
  destfile <- "dolartoday.xlsx" #
  curl::curl_download(url, destfile)#
  dolartoday <- read_excel(destfile, col_types = c("text","numeric", "numeric", "text", "numeric","numeric"))#
  
  dolarparalelo=as.data.frame(dolartoday[,1:3]) #
  
  colnames(dolarparalelo)<-c("Fecha","Bs.","Bs.S") #
  
  dolarparalelo[,1]=as.Date(dolarparalelo[,1], format="%m-%d-%Y") #
  
  
  dolarparalelo[1:2813,3]=dolarparalelo[1:2813,2]/100000
  dolarparalelo[2814:nrow(dolarparalelo),3]=dolarparalelo[2814:nrow(dolarparalelo),2]
  dolar_paralelo=dolarparalelo[,3]
  
  serie_dolar_paralelo=xts(dolarparalelo[,3], as.Date(dolarparalelo$Fecha))
  
  
  #Highchart Bs.S
  grafico_dolar_paralelo=hchart(serie_dolar_paralelo, name = "USD/Bs.")
  
  
  precio_actual=dolar_paralelo[nrow(as.data.frame(dolar_paralelo))]
  
  datos=list("grafico"=grafico_dolar_paralelo,"dolar"=dolar_paralelo,"serie"=serie_dolar_paralelo, 
             precio_actual)
  
  return(datos)
  
}

dolar=datos_dolar()
dolar$grafico



```

### Inflaci贸n mensual

```{r echo=FALSE, message=FALSE, warning=FALSE}
datos_inflacion <-function(directorio_archivo_1){
  
  library(dygraphs)
  library(xts)
  library(readr)
  library(readxl)
  library(zoo)
  library(dplyr)
  library(magrittr)
  library(highcharter)
  
  inflacion_mensual= read_excel(directorio_archivo_1, col_types = c("date", "numeric"))

  
  #Construccion de serie de inflacion mensual
  serie_inflacion_mensual=xts(inflacion_mensual[,2], inflacion_mensual$Fecha)
  

  #Highchart 
  grafico_inflacion_mensual=hchart(serie_inflacion_mensual,name = "Inflaci贸n %")
  
  
  
  return(grafico_inflacion_mensual)
  
}

inflacion=datos_inflacion("C:/Users/analista04/Documents/R/grupointeraval.github.io//3_inflacion_mensual.xlsx")
inflacion
```

### Liquidez Monetaria

```{r echo=FALSE, message=FALSE, warning=FALSE}
m2 <- function(){

library(readxl)
liquidez <- read_excel("C:/Users/analista04/Documents/R/grupointeraval.github.io//liquidez.xlsx", 
                       col_types = c("date", "numeric", "numeric")) 
liquidez=as.data.frame(liquidez)
liquidez=liquidez[2:nrow(liquidez),]

library(dygraphs)
library(xts)
library(readr)
library(readxl)
library(zoo)
library(dplyr)
library(magrittr)
library(highcharter)

m2=liquidez[,2]
serie_m2=xts(liquidez[,3], as.Date(liquidez$fecha))

grafico_m2=hchart(serie_m2, name = "% Var. M2")

datos=list("grafico"=grafico_m2,"liquidez_m2"=m2,"serie_m2"=serie_m2)


return(datos)

}


liquidez=m2()
liquidez$grafico

```

