---
title: "Reporte Diario"
author: "Grupo Interaval"
date: '`r paste("Datos para el ", Sys.Date())`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Compras y venta

A continuación se muestra gráficamente la distribución de compras (puntos rojos) y ventas (puntos azules) por acción a partir de su tenencia en cartera propia:

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

file.remove("Reporte.xlsx")
library(googledrive)
library(readxl)
library(readr)
library(xts)
library(ggplot2)
drive_download("Reporte", type = "xlsx")
cartera <- read_excel("Reporte.xlsx", sheet = "ABC.A")
View(cartera)

cartera=as.data.frame(cartera)


##########################

accion <- read_delim("C:/Users/analista04/Documents/R/grupointeraval.github.io/abc.a.txt", 
                     "|", escape_double = FALSE, col_names = FALSE, 
                     col_types = cols(X1 = col_skip(), X11 = col_skip(), 
                                      X2 = col_datetime(format = "%d/%m/%Y ")), 
                     locale = locale(decimal_mark = ",", grouping_mark = "."), 
                     trim_ws = TRUE)

accion=as.data.frame(accion)
colnames(accion)<-c("Fecha","Tipo.de.operacion",paste("ABCA",".Open",sep=""),paste("ABCA",".Close",sep=""),
                    paste("ABCA",".High",sep=""),paste("ABCA",".Low",sep=""),
                    ".Cantidad.de.Operaciones",paste("ABCA",".Volume",sep=""),".Monto.Efectivo")

accion=accion[c("Fecha", paste("ABCA",".Open",sep=""), paste("ABCA",".High",sep=""), 
                paste("ABCA",".Low",sep=""), paste("ABCA",".Close",sep=""), paste("ABCA",".Volume",sep=""), 
                ".Cantidad.de.Operaciones", ".Monto.Efectivo", "Tipo.de.operacion") ]


url <- "https://dxj1e0bbbefdtsyig.woldrssl.net/custom/dolartoday.xlsx"#
destfile <- "dolartoday.xlsx" #
curl::curl_download(url, destfile)#
dolartoday <- read_excel(destfile, col_types = c("text","numeric", "numeric", "text", "numeric","numeric"))#

dolarparalelo=as.data.frame(dolartoday[,1:3]) #

colnames(dolarparalelo)<-c("Fecha","Bs.","Bs.S") #

dolarparalelo[,1]=as.Date(dolarparalelo[,1], format="%m-%d-%Y") #

#dolarparalelo <- read_excel(directorio, col_types = c("date", "numeric", "numeric"))

dolarparalelo[1:2813,3]=dolarparalelo[1:2813,2]/100000
dolarparalelo[2814:nrow(dolarparalelo),3]=dolarparalelo[2814:nrow(dolarparalelo),2]

serie_dolar_paralelo=xts(dolarparalelo[,3], as.Date(dolarparalelo$Fecha))


fechas_cotizaciones=as.Date(intersect(as.Date(dolarparalelo$Fecha),as.Date(accion$Fecha)))

accion_usd=accion[as.Date(accion$Fecha) %in% fechas_cotizaciones, ]



for (i in 1:nrow(as.data.frame(intersect(as.Date(dolarparalelo$Fecha),as.Date(accion$Fecha))))) {
  
  s=accion_usd[accion_usd$Fecha==fechas_cotizaciones[i],2:7]
  r=as.numeric(dolarparalelo[as.Date(dolarparalelo$Fecha)==fechas_cotizaciones[i],2])
  
  accion_usd[accion_usd$Fecha==fechas_cotizaciones[i],2:7]=s/r
  
}

####################################
###################### DEBE SER MAYOR O IGUAL A LA PRIMERA FECHA DE COMPRA

accion_usd=accion_usd[accion_usd$Fecha>=cartera$Inicio[1],]
venta=cartera[complete.cases(cartera$`Venta de acciones`),]
compra = ggplot() + 
  geom_line(data = accion_usd, aes(x = accion_usd$Fecha, y = accion_usd$ABCA.Close), size=0.5, color="#999999") +
  geom_point(data = cartera, aes(x = cartera$Inicio, y = cartera$`Precio en Dolares`), color = "red") +
  geom_point(data = venta, aes(x = venta$Inicio, y = venta$`Precio en Dolares`), color = "blue") +
  xlab('Fecha')+
  ylab('Cotización en Dólares')+ ylim(0,max(accion_usd$ABCA.Close)*1.1)


compra


```

